[package]
name = "film_exif_fixer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
dirs = "5.0.1"
dotenv = "0.15.0"
log = "0.4.22"
pretty_env_logger = "0.5.0"
snafu = "0.8.3"
strum = "0.26.3"
strum_macros = "0.26.4"